// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"readmark/ent/post"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pc *PostCreate) SetCreatedAt(t time.Time) *PostCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PostCreate) SetNillableCreatedAt(t *time.Time) *PostCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PostCreate) SetUpdatedAt(t time.Time) *PostCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PostCreate) SetNillableUpdatedAt(t *time.Time) *PostCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetUserID sets the "user_id" field.
func (pc *PostCreate) SetUserID(u uint) *PostCreate {
	pc.mutation.SetUserID(u)
	return pc
}

// SetSite sets the "site" field.
func (pc *PostCreate) SetSite(s string) *PostCreate {
	pc.mutation.SetSite(s)
	return pc
}

// SetPath sets the "path" field.
func (pc *PostCreate) SetPath(s string) *PostCreate {
	pc.mutation.SetPath(s)
	return pc
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (pc *PostCreate) SetNillablePath(s *string) *PostCreate {
	if s != nil {
		pc.SetPath(*s)
	}
	return pc
}

// SetPid sets the "pid" field.
func (pc *PostCreate) SetPid(s string) *PostCreate {
	pc.mutation.SetPid(s)
	return pc
}

// SetReadLastReplyID sets the "read_last_reply_id" field.
func (pc *PostCreate) SetReadLastReplyID(s string) *PostCreate {
	pc.mutation.SetReadLastReplyID(s)
	return pc
}

// SetNillableReadLastReplyID sets the "read_last_reply_id" field if the given value is not nil.
func (pc *PostCreate) SetNillableReadLastReplyID(s *string) *PostCreate {
	if s != nil {
		pc.SetReadLastReplyID(*s)
	}
	return pc
}

// SetReadLastReplyIndex sets the "read_last_reply_index" field.
func (pc *PostCreate) SetReadLastReplyIndex(i int) *PostCreate {
	pc.mutation.SetReadLastReplyIndex(i)
	return pc
}

// SetNillableReadLastReplyIndex sets the "read_last_reply_index" field if the given value is not nil.
func (pc *PostCreate) SetNillableReadLastReplyIndex(i *int) *PostCreate {
	if i != nil {
		pc.SetReadLastReplyIndex(*i)
	}
	return pc
}

// SetReadLastReplyTime sets the "read_last_reply_time" field.
func (pc *PostCreate) SetReadLastReplyTime(t time.Time) *PostCreate {
	pc.mutation.SetReadLastReplyTime(t)
	return pc
}

// SetNillableReadLastReplyTime sets the "read_last_reply_time" field if the given value is not nil.
func (pc *PostCreate) SetNillableReadLastReplyTime(t *time.Time) *PostCreate {
	if t != nil {
		pc.SetReadLastReplyTime(*t)
	}
	return pc
}

// SetMarkBanned sets the "mark_banned" field.
func (pc *PostCreate) SetMarkBanned(b bool) *PostCreate {
	pc.mutation.SetMarkBanned(b)
	return pc
}

// SetNillableMarkBanned sets the "mark_banned" field if the given value is not nil.
func (pc *PostCreate) SetNillableMarkBanned(b *bool) *PostCreate {
	if b != nil {
		pc.SetMarkBanned(*b)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PostCreate) SetID(u uint) *PostCreate {
	pc.mutation.SetID(u)
	return pc
}

// Mutation returns the PostMutation object of the builder.
func (pc *PostCreate) Mutation() *PostMutation {
	return pc.mutation
}

// Save creates the Post in the database.
func (pc *PostCreate) Save(ctx context.Context) (*Post, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PostCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PostCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PostCreate) check() error {
	if _, ok := pc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Post.user_id"`)}
	}
	if _, ok := pc.mutation.Site(); !ok {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required field "Post.site"`)}
	}
	if _, ok := pc.mutation.Pid(); !ok {
		return &ValidationError{Name: "pid", err: errors.New(`ent: missing required field "Post.pid"`)}
	}
	return nil
}

func (pc *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.UserID(); ok {
		_spec.SetField(post.FieldUserID, field.TypeUint, value)
		_node.UserID = value
	}
	if value, ok := pc.mutation.Site(); ok {
		_spec.SetField(post.FieldSite, field.TypeString, value)
		_node.Site = value
	}
	if value, ok := pc.mutation.Path(); ok {
		_spec.SetField(post.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := pc.mutation.Pid(); ok {
		_spec.SetField(post.FieldPid, field.TypeString, value)
		_node.Pid = value
	}
	if value, ok := pc.mutation.ReadLastReplyID(); ok {
		_spec.SetField(post.FieldReadLastReplyID, field.TypeString, value)
		_node.ReadLastReplyID = value
	}
	if value, ok := pc.mutation.ReadLastReplyIndex(); ok {
		_spec.SetField(post.FieldReadLastReplyIndex, field.TypeInt, value)
		_node.ReadLastReplyIndex = value
	}
	if value, ok := pc.mutation.ReadLastReplyTime(); ok {
		_spec.SetField(post.FieldReadLastReplyTime, field.TypeTime, value)
		_node.ReadLastReplyTime = value
	}
	if value, ok := pc.mutation.MarkBanned(); ok {
		_spec.SetField(post.FieldMarkBanned, field.TypeBool, value)
		_node.MarkBanned = value
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (pcb *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Post, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PostCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
